eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
#      defaultZone: http://discovery-service:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/student_accommodation
          jwk-set-uri: http://keycloak:8080/realms/student_accommodation/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        web:
          cors : DEBUG
