spring:
  cloud:
    config:
      enabled: true
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/etudiant_db?createDatabaseIfNotExist=true
    username: hello
    password: hello
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8089
  servlet:
    context-path: /

